<?php include "../includes/header.php"; ?>

<style type="text/css">
    #email-marketing img{max-width: 35%;}
    @media (max-width: 991px) {
        #email-marketing img{max-width: 60%;}
    }
    @media (max-width: 767px) {
        #email-marketing img{max-width: 30%;}
    }
    @media (max-width: 575px) {
        #email-marketing img{max-width: 50%;}
    }
</style>


    <div class="pagetitle">
        <div class="container">
             <h1>eZee Absolute-Supplementary Features</h1>
            <!--<h5>Find out what eZee PMS can do for your hotel</h5>-->
        </div>
    </div>
    
    <div class="page_container" style="padding-bottom:0; padding-top:0;">
        <div class="fullsection featureset" id="profile-mgnt" style="padding-top: 60px;">
            <div class="container">
                <h2 style="margin-top:0;" class="text-center">Profile Management</h2>
                <p class="text-center">With the help of eZee Absolute, you can easily manage multiple guest profiles as well as effortlessly maintain various booking sources such as travel agents, room owners etc.</p>
                <div class="text-center">
                    <img src="../images/profile-mgnt.png" alt="Profile Management" />
                </div>
                <br />
                <div class="row pmsrw2">
                    <div class="col-sm-6">
                        <div class="fgp-list">
                            <h3 class="fgp-title">Corporate Guest Profile</h3>
                            <p>Facilitating your corporate guests, you can create a custom company profile which will store all the information of all your guests associated with the company. You can easily identify and efficiently manage any company’s guests at your property.</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="fgp-list">
                            <h3 class="fgp-title">Room Owner Profile</h3>
                            <p>You can even manage the rooms by room owner’s profile in which rooms are assigned to owners. Since these owners are considered as investors of the property, you need to pay them commission for the revenue generated by these rooms.</p>
                        </div>
                    </div>
                </div>
                <div class="row pmsrw1">
                    <div class="col-sm-6">
                        <div class="fgp-list">
                            <h3 class="fgp-title">Travel Agent Profile</h3>
                            <p>An extensive source of bookings, OTAs have proved to be an integral part of a hotel’s online business strategy. The PMS will let you manage Travel Agent accounts, wherein you’ll be able to calculate the commissions, track pending payments and handle invoices, consequently reducing your time consumed over offline bookings.</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="fgp-list">
                            <h3 class="fgp-title">Business Source Profile</h3>
                            <p>Organizing various business source profiles helps you in maintaining records of all the transactions between your hotel and various third party services associated with it, such as car rentals, travel agents, etc. Besides, your payments are bifurcated with due amount from your end and the agent. Set up special tariffs or reserve rooms for particular business sources as you need.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="fullsection graybg featureset" id="user-privilege">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 text-center">
                        <img src="../images/user-privilege.png" class="user-privi" alt="User Privilege Level & Security Control" />
                    </div>
                    <div class="col-sm-8">
                        <br />
                        <h2>User Privilege & Security Control</h2>
                        <p>Create multiple user accounts and divide your front office task amongst them. eZee Absolute allows to you create numerous user accounts accessing the system simultaneously. Additionally, you can also add an extra level of security by providing user level access privileges restricting the staff access to sensitive data.</p>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="fullsection featureset" id="email-marketing">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Email Marketing and Scheduling</h2>
                        
                        <div class="filist">
                            <h3>Pre-arrival and Post-departure Emails</h3>
                            <p>eZee's online reservation system gives you the facility to send out automatic emails ranging from pre-arrival to post-departure for enriching guest engagement. These emails can be opportunities for the guests to change their bookings, guest satisfaction surveys, bring back emails and more.</p>
                        </div>
                <?php /*
                        <div class="filist">
                            <h3>Promotional / Newsletter Emails</h3>
                            <p>The system allows you to send out promotional emails with special offers and secret codes to your guests. Once you set the conditions, the PMS will automatically pick up the guest email from the database, publish the promotional campaign attracting more returning guests. In addition, you can send out secret deals to your regular guests and other promotional emails, inviting them to your hotel.</p>
                        </div>
                */ ?>
                        <div class="filist">
                            <h3>In-House Emails</h3>
                            <p>The automatic emails can be sent to the in-house guest to update them regarding the hotel renovations, today’s menu or to pass them important information and more.</p>
                        </div>
                    </div>
                    <div class="col-sm-6 text-center">
                        <img src="../images/email-feature-marketing.png" alt="Email Marketing and Scheduling" />
                    </div>
                </div>
                
            </div>
        </div>
         <div class="fullsection featureset review-sale" id="9">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h2>More Reviews Means More ROI</h2>
                        <img src="../images/review-sale.png" alt="More Reviews Means More ROI" />
                        <p>An integral part of communication between you and the guest, hotel reviews help the booker to call shots on his stay with you. The reservation software will email your guest during check-out, to review their stay experience with you; consequently publishing the confirmed review on your hotel website or other review sites.</p>
                    </div>
                </div>
            </div>
        </div>
        <?php include '../includes/footer-features.php' ?>
    </div>

<?php include "../includes/footer.php"; ?>

<script>
    $(function() {
        /*$('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top - 70
                    }, 800);
                    return false;
                }
            }
        });*/
        var locatHash = window.location.hash;
        if(locatHash != ""){
            $('html, body').animate({scrollTop : $(locatHash).offset().top - 70},1500);
        }
    });
</script>